version: 2.0.0-build.{build}

image: Visual Studio 2019

branches:
  only:
    - main
    - /feature\/.+/

environment:
  MYGET_API_KEY:
    secure: 3tEiaoqZlTJcJkAX+3wWyp3mbCYuJpALEFzTEaum6ACiXbWgsa1kWYGBi3TUFY7c
  MYGET_FEED: https://www.myget.org/F/consolefx/api/v2/package
  CODECOV_TOKEN: 9393205e-cfa3-459f-a3d4-af5c04c3410d
  MYGET_SYMBOLS_FEED: https://www.myget.org/F/consolefx/symbols/api/v2/package
  MYGET_SYMBOLS_API_KEY:
    secure: 3tEiaoqZlTJcJkAX+3wWyp3mbCYuJpALEFzTEaum6ACiXbWgsa1kWYGBi3TUFY7c

install:
- pwsh: dotnet --list-sdks
- pwsh: choco install codecov
- ps: ./.scripts/install-dotnet-sdk.ps1

build_script:
- pwsh: ./.scripts/build.ps1

test_script:
- pwsh: ./.scripts/test.ps1
- pwsh: ./.scripts/cc-codecov.ps1

deploy_script:
- pwsh: ./.scripts/deploy.ps1
