//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleFx.CmdLineArgs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleFx.CmdLineArgs.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is not a valid name..
        /// </summary>
        internal static string Arg_Invalid_name {
            get {
                return ResourceManager.GetString("Arg_Invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify at least one name.
        /// </summary>
        internal static string Arg_No_names_specified {
            get {
                return ResourceManager.GetString("Arg_No_names_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument named &apos;{0}&apos; already exists in the argument collection..
        /// </summary>
        internal static string Arguments_Duplicate_argument {
            get {
                return ResourceManager.GetString("Arguments_Duplicate_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format string should contain a format placeholder ({0}) to specify where the parameter value is inserted..
        /// </summary>
        internal static string Option_MissingPlaceholderInFormatString {
            get {
                return ResourceManager.GetString("Option_MissingPlaceholderInFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator at index {0} is null..
        /// </summary>
        internal static string Option_ValidatorIsNull {
            get {
                return ResourceManager.GetString("Option_ValidatorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify at least one validator..
        /// </summary>
        internal static string Option_ValidatorsNotSpecified {
            get {
                return ResourceManager.GetString("Option_ValidatorsNotSpecified", resourceCulture);
            }
        }
    }
}
