//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleFx.CmdLineArgs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleFx.CmdLineArgs.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of arguments specified.
        /// </summary>
        public static string InvalidNumberOfArguments {
            get {
                return ResourceManager.GetString("InvalidNumberOfArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;{0}&quot; should be followed by a colon (:) to specify its parameters.
        /// </summary>
        public static string InvalidOptionParameterSpecifier {
            get {
                return ResourceManager.GetString("InvalidOptionParameterSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter format for option &quot;{0}&quot;.
        /// </summary>
        public static string InvalidOptionParametersSpecified {
            get {
                return ResourceManager.GetString("InvalidOptionParametersSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option was specified: &quot;{0}&quot;.
        /// </summary>
        public static string InvalidOptionSpecified {
            get {
                return ResourceManager.GetString("InvalidOptionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters specified for option &apos;{0}&apos;.
        /// </summary>
        public static string InvalidParametersSpecified {
            get {
                return ResourceManager.GetString("InvalidParametersSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurence/parameter values cannot be negative.
        /// </summary>
        public static string OccurenceParameterValueNegative {
            get {
                return ResourceManager.GetString("OccurenceParameterValueNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An option by the name &apos;{0}&apos; already exists.
        /// </summary>
        public static string OptionAlreadyExists {
            get {
                return ResourceManager.GetString("OptionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options should be specified after the arguments.
        /// </summary>
        public static string OptionsAfterParameters {
            get {
                return ResourceManager.GetString("OptionsAfterParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options should be specified before the arguments.
        /// </summary>
        public static string OptionsBeforeParameters {
            get {
                return ResourceManager.GetString("OptionsBeforeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify required arguments after optional ones.
        /// </summary>
        public static string RequiredArgumentsDefinedAfterOptional {
            get {
                return ResourceManager.GetString("RequiredArgumentsDefinedAfterOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option &quot;{0}&quot; should be specified.
        /// </summary>
        public static string RequiredOptionAbsent {
            get {
                return ResourceManager.GetString("RequiredOptionAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameters absent for option &apos;{0}&apos;.
        /// </summary>
        public static string RequiredParametersAbsent {
            get {
                return ResourceManager.GetString("RequiredParametersAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; option should be specified at least {1} times..
        /// </summary>
        public static string TooFewOptions {
            get {
                return ResourceManager.GetString("TooFewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; option cannot be specified more than {1} times..
        /// </summary>
        public static string TooManyOptions {
            get {
                return ResourceManager.GetString("TooManyOptions", resourceCulture);
            }
        }
    }
}
